package pl.skidam.automodpack_core.utils;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class FileTreeScannerTest {

    @TempDir
    Path testFilesDir;

    private FileTreeScanner fileTreeScanner;
    private Set<Path> expectedPaths;

    @BeforeEach
    void setUp() throws IOException {
        createTestFileStructure();

        var rules = Set.of(
                "/file.txt",
                "/config/config*",
                "/config/mod-config.toml",
                "/mods/*.jar",
                "!/mods/server-*jar",
                "!/mods/*19.jar",
                "!/shaders/*.txt",
                "/thisfiledoesnotexist.txt",
                "/shaders/*",
                "!/shaders/notashader.zip",
                "/f*/**",
                "/directory/*/*"
        );

        fileTreeScanner = new FileTreeScanner(rules, Set.of(testFilesDir));
        fileTreeScanner.scan();

        // Define expected paths relative to temp dir for clarity
        expectedPaths = Set.of(
                testFilesDir.resolve("file.txt"),
                testFilesDir.resolve("config/config.json"),
                testFilesDir.resolve("config/config-mod.json5"),
                testFilesDir.resolve("config/mod-config.toml"),
                testFilesDir.resolve("mods/mod-1.20.jar"),
                testFilesDir.resolve("mods/client-mod-1.20.jar"),
                testFilesDir.resolve("shaders/shader1.zip"),
                testFilesDir.resolve("shaders/shader2.zip"),
                testFilesDir.resolve("shaders/shader3.zip"),
                testFilesDir.resolve("foo/file.json"),
                testFilesDir.resolve("foo/bar/file.json"),
                testFilesDir.resolve("foo/boo/file.json"),
                testFilesDir.resolve("foo/boo/file.toml"),
                testFilesDir.resolve("foo/poo/file.json"),
                testFilesDir.resolve("foo/poo/moo/file.json"),
                testFilesDir.resolve("foo/poo/moo/file2.json"),
                testFilesDir.resolve("directory/which/file.json"),
                testFilesDir.resolve("directory/who/file.json")
        );
    }

    @Test
    void shouldFindAllExpectedFiles() {
        Set<Path> actualPaths = new HashSet<>(fileTreeScanner.getMatchedPaths().values());

        // Check size first for quick failure
        assertEquals(expectedPaths.size(), actualPaths.size(), "Number of matched files does not match expected count.");

        // Verify content matches exactly (ignoring order)
        assertEquals(expectedPaths, actualPaths, "The set of matched files differs from expectation.");
    }

    @Test
    void shouldExcludeBlacklistedFiles() {
        var matches = fileTreeScanner.getMatchedPaths().values();

        assertAll("Blacklist checks",
                () -> assertFalse(matches.contains(testFilesDir.resolve("mods/server-mod-1.20.jar")), "Should exclude server mods"),
                () -> assertFalse(matches.contains(testFilesDir.resolve("mods/server-mod-1.19.jar")), "Should exclude server mods"),
                () -> assertFalse(matches.contains(testFilesDir.resolve("mods/client-mod-1.19.jar")), "Should exclude *19.jar"),
                () -> assertFalse(matches.contains(testFilesDir.resolve("mods/mod-1.19.jar")), "Should exclude *19.jar"),
                () -> assertFalse(matches.contains(testFilesDir.resolve("shaders/notashader.zip")), "Should exclude specific blacklisted file")
        );
    }

    @Test
    void shouldPruneIrrelevantDirectories() {
        // "mods/mod" is a file in a valid folder, but shouldn't match *.jar
        assertFalse(fileTreeScanner.getMatchedPaths().containsValue(testFilesDir.resolve("mods/mod")));

        // "config/random-options.txt" shouldn't match config* or mod-config.toml
        assertFalse(fileTreeScanner.getMatchedPaths().containsValue(testFilesDir.resolve("config/random-options.txt")));
    }

    @Test
    void shouldHandleNonExistentFilesGracefully() {
        assertFalse(fileTreeScanner.getMatchedPaths().containsValue(testFilesDir.resolve("thisfiledoesnotexist.txt")));
    }

    @Test
    void shouldNotIncludeDirectoriesInResults() {
        // Ensure only files are returned, not directories matching the wildcard
        assertFalse(fileTreeScanner.getMatchedPaths().containsValue(testFilesDir.resolve("shaders")));
    }

    @Test
    void fileMatchesShouldReturnTrueForFoundFiles() {
        // Test the fileMatches(String) method using the keys generated by the WildCards instance
        Set<String> keys = fileTreeScanner.getMatchedPaths().keySet();
        for (String key : keys) {
            assertTrue(fileTreeScanner.hasMatch(key), "fileMatches() should return true for key: " + key);
        }
    }

    // --- Helper Methods ---

    private void createTestFileStructure() throws IOException {
        createFile("file.txt");

        createFile("config/config.json");
        createFile("config/config-mod.json5");
        createFile("config/mod-config.toml");
        createFile("config/random-options.txt");

        createFile("mods/mod-1.20.jar");
        createFile("mods/mod-1.19.jar");
        createFile("mods/client-mod-1.20.jar");
        createFile("mods/client-mod-1.19.jar");
        createFile("mods/server-mod-1.20.jar");
        createFile("mods/server-mod-1.19.jar");
        createFile("mods/mod"); // No extension

        createFile("mods/random directory/mod-1.19.jar");
        createFile("mods/random directory/client-mod-1.19.jar");
        createFile("mods/random directory/client-mod-1.20.jar");
        createFile("mods/random directory/mod");
        createFile("mods/random directory/random-config.yaml");

        createFile("shaders/shader1.zip");
        createFile("shaders/shader2.zip");
        createFile("shaders/shader3.zip");
        createFile("shaders/notashader.zip");
        createFile("shaders/shaderconfig.txt");

        createFile("foo/file.json");
        createFile("foo/bar/file.json");
        createFile("foo/boo/file.json");
        createFile("foo/boo/file.toml");
        createFile("foo/poo/file.json");
        createFile("foo/poo/moo/file.json");
        createFile("foo/poo/moo/file2.json");

        createFile("directory/file.json"); // Parent dir match check
        createFile("directory/which/file.json");
        createFile("directory/who/file.json");
    }

    private void createFile(String relativePath) throws IOException {
        Path file = testFilesDir.resolve(relativePath);
        Files.createDirectories(file.getParent());
        Files.createFile(file);
    }
}