#!/usr/bin/env bash
# Rebuilds the committed Windows native from source and refreshes its receipt.
#
# Same-toolchain rebuilds are byte-identical: the build flags fix the PE timestamp and
# image base, and the output name must stay win_file_stat.dll because mingw embeds it as
# the DLL's internal export name. Cross-toolchain builds are NOT byte-identical, so the
# commit ships a receipt (natives-receipt.txt) naming the exact sources and DLL it was
# built from; CI compiles the C with mingw to prove the sources build and the receipt
# check proves the committed DLL was not left behind by a source edit.
#
# Requires: x86_64-w64-mingw32-gcc (mingw-w64) on PATH and JAVA_HOME pointing at
# a JDK (any version; only jni.h is used).
set -euo pipefail

c="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repo="$(cd "$c/../../../.." && pwd -P)"
dll="core/src/main/resources/natives/windows-x86_64/win_file_stat.dll"

command -v x86_64-w64-mingw32-gcc >/dev/null || { echo "error: x86_64-w64-mingw32-gcc not on PATH (install mingw-w64)" >&2; exit 1; }
: "${JAVA_HOME:?error: JAVA_HOME must point at a JDK (jni.h is required)}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
x86_64-w64-mingw32-gcc -c -O0 -fno-PIC -fno-ident -o "$work/pe_reloc.o" "$c/pe_reloc.c"
x86_64-w64-mingw32-gcc -shared -s -Os -fno-ident -fPIC -fno-stack-protector -fno-asynchronous-unwind-tables -fno-unwind-tables -nostdlib -Wl,--gc-sections -Wl,--enable-reloc-section -Wl,--dynamicbase -Wl,--high-entropy-va -Wl,--no-insert-timestamp -Wl,--image-base,0x6BCB5F440000 -Wl,-e,DllMain -Wl,-u,win_file_stat_keep -I "$c" -I "$JAVA_HOME/include" -o "$repo/$dll" "$c/windows_file_stat.c" "$work/pe_reloc.o" -lkernel32
cd "$repo"
{
	echo "# Generated by core/src/main/c/rebuild-windows-natives.sh - commit together with the DLL it names."
	sha256sum core/src/main/c/windows_file_stat.c core/src/main/c/pe_reloc.c core/src/main/c/jni_md.h "$dll"
} > core/src/main/c/natives-receipt.txt
cat core/src/main/c/natives-receipt.txt
